# Generated by Django 5.1.3 on 2024-11-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_rename_genres_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
