# Generated by Django 5.1.3 on 2024-11-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('US', 'Estados Unidos'), ('UK', 'Reino Unido'), ('FR', 'França'), ('DE', 'Alemanha'), ('IT', 'Itália'), ('JP', 'Japão'), ('KR', 'Coreia do Sul'), ('CN', 'China'), ('RU', 'Russia'), ('IN', 'India'), ('BR', 'Brasil'), ('AU', 'Australia'), ('CA', 'Canada'), ('MX', 'Mexico'), ('ES', 'Espanha'), ('AR', 'Argentina'), ('CO', 'Colombia'), ('PE', 'Peru'), ('CL', 'Chile'), ('VE', 'Venezuela'), ('EC', 'Equador'), ('BO', 'Bolivia'), ('PY', 'Paraguay'), ('UY', 'Uruguay'), ('CR', 'Costa Rica'), ('PA', 'Panama'), ('CU', 'Cuba'), ('DO', 'Dominican Republic'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('SV', 'El Salvador'), ('NI', 'Nicaragua'), ('PR', 'Puerto Rico'), ('JM', 'Jamaica'), ('BS', 'Bahamas'), ('HT', 'Haiti'), ('BB', 'Barbados'), ('TT', 'Trinidad and Tobago'), ('AG', 'Antigua and Barbuda'), ('DM', 'Dominica'), ('VC', 'Saint Vincent and the Grenadines'), ('GD', 'Grenada'), ('KN', 'Saint Kitts and Nevis'), ('LC', 'Saint Lucia'), ('SR', 'Suriname')], max_length=100, null=True)),
                ('biography', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
